app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, DateField, BooleanField
from wtforms.validators import DataRequired

class EditProfilForm(FlaskForm):
    """
    Form edit profil
    """
    username = StringField('Username', validators=[DataRequired()])
    namaDepan = StringField('Nama Depan', validators=[DataRequired()])
    namaBelakang = StringField('Nama Belakang', validators=[DataRequired()])
    noHp = IntegerField('Nomor HP', validators=[DataRequired()])
    tglLahir = DateField('Tanggal Lahir', format='%Y-%m-%d', validators=[DataRequired()])
    submit = SubmitField('Simpan Profil')

app/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from . import views

app/user/views.py
from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import user
from forms import EditProfilForm
from .. import db
from ..models import Barang, User


@user.route('/profil')
@login_required
def profil():
    """
    Profil User
    """
    #query barang jualan si user
    jualan = db.session.query(Barang).filter(Barang.id_user==current_user.id_user).all()
    return render_template('user/profil.html', jualan=jualan, title='Profil')

@user.route('/profil/edit/<user>', methods=['GET', 'POST'])
@login_required
def edit_profil(user):
    """
    Edit Profil
    """
    user = db.session.query(User).filter(User.username==user).first()
    form = EditProfilForm(obj=user)
    if form.validate_on_submit():
        user.username=form.username.data,
        user.nama_depan=form.namaDepan.data,
        user.nama_belakang=form.namaBelakang.data,
        user.tgl_lahir=form.tglLahir.data,
        user.no_hp=form.noHp.data,
        db.session.commit()
        flash('Profil berhasil diedit')

        return redirect(url_for('user.profil', username=current_user.username))

    form.username.data=user.username
    form.namaDepan.data=user.nama_depan
    form.namaBelakang.data=user.nama_belakang
    form.tglLahir.data=user.tgl_lahir
    form.noHp.data=user.no_hp
    return render_template('user/edit_profil.html', action="Edit", form=form, user=user, title="Edit Profil")

app/templates/user/edit_profil.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Edit Profil {{current_user.username}} {% endblock %}
{% block body %}
<div class="tile is-ancestor">
    <div class="tile is-parent">
        <div class="tile is-child box has-background-light is-shadowless">
            <div class="title has-text-danger">Edit Profil</div>
            <div class="box">
                <article class="columns">
                    <div class="column is-3-desktop">
                        <figure class="image is-128x128 center">
                            <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
                        </figure>
                    </div>
                    <div class="column is-9-desktop">
                        <div class="content">
                            <form method='POST' role='form'>
                                {{ form.hidden_tag() }}
                                {{ wtf.form_errors(form, hiddens="only") }}

                                {{ wtf.form_field(form.username, class="input") }} <br>
                                {{ wtf.form_field(form.namaDepan, class="input") }} <br>
                                {{ wtf.form_field(form.namaBelakang, class="input") }} <br>
                                {{ wtf.form_field(form.noHp, class="input") }} <br>
                                {{ wtf.form_field(form.tglLahir, class="input", type="date") }} <br>
                                {{ wtf.form_field(form.submit, class="button is-primary is-outlined") }}
                            </form>
                        </div>
                    </div>
                </article>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/user/profil.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Profil {{current_user.username}} {% endblock %}
{% block body %}

{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
    <div class="notification is-success">
        {{ message }}
    </div>
    {% endfor %}
  {% endif %}
{% endwith %}
<div class="tile is-ancestor">
    <div class="tile is-parent is-4">
        <div class="tile is-child box has-background-light is-shadowless">
            <div class="title has-text-danger">Profil</div>
            <div class="box">
                <article class="media">
                    <div class="media-left">
                        <figure class="image is-64x64">
                            <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
                        </figure>
                    </div>
                    <div class="media-content">
                        <div class="content">
                            <p>
                            <strong>{{ current_user.nama_depan|upper }} {{current_user.nama_belakang|upper }}</strong> @{{ current_user.username }}
                            <br>
                            {{ current_user.jurusan.fakultas.nama_fakultas }}
                            <br>
                            {{ current_user.jurusan.nama_jurusan }}
                            </p>
                        </div>
                        <a class="button is-primary is-outlined" href="{{ url_for('user.edit_profil', user=current_user.username) }}">Edit</a>
                    </div>
                </article>
            </div>
        </div>
    </div>
    <div class="tile is-parent">
        <div class="tile is-child box has-background-light is-shadowless">
            <div class="title has-text-danger">Dijual</div>
            <div class="columns is-multiline">
                {% for barang in jualan %}
                    <div class="column is-one-quarter-desktop">
                        <a href="{{ url_for('barang.detail_barang', idbarang=barang.id_barang)}} " style="text-decoration: none">
                            <div class="card">
                                <div class="card-image">
                                    <figure class="image is-4by3">
                                        <img src="{{ barang.foto_barang }}" alt="{{ barang.nama_barang }}">
                                    </figure>
                                </div>
                                <div class="card-content">
                                    <div class="media">
                                        <div class="media-content">
                                            <p class="is-size-6"><strong>{{ barang.nama_barang }}</strong></p>
                                            <p class="is-size-7"><i class="far fa-user"></i> {{ barang.barang.username }}</p>
                                            <p class="subtitle is-7"><i class="fas fa-map-marker-alt"></i> {{ barang.jurusan.nama_jurusan }}</p>
                                        </div>
                                    </div>
                                    <div class="content">
                                        <span class=" title is-6 has-text-danger">{{ "Rp {:,}".format(barang.harga_barang).replace(',','.') }}</span>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}