app/barang/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import StringField, IntegerField, SubmitField, BooleanField, FileField
from wtforms.validators import DataRequired
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from .. import db, photos

class FormBarang(FlaskForm):
    """
    Form barang baru / edit
    """
    namaBarang = StringField('Nama Barang', validators=[DataRequired()])
    hargaBarang = IntegerField('Harga Barang', validators=[DataRequired()])
    garansiBarang = BooleanField('Garansi')
    fotoBarang = FileField('Foto Barang', validators=[FileAllowed(photos, 'Hanya upload file gambar!'), FileRequired('Belum ada gambar barang!')])
    submit = SubmitField('Posting')

app/barang/__init__.py
from flask import Blueprint

barang = Blueprint('barang', __name__)

from . import views

app/barang/views.py
from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import barang
from forms import FormBarang
from .. import db, photos
from ..models import User, Barang, Jurusan

def check_admin():
    """
    Mencegah non-admin user untuk masuk
    """
    if not current_user.is_admin:
        abort(403)

@barang.route('/barang/details/<idbarang>', methods=['GET', 'POST'])
def detail_barang(idbarang):

    barang = db.session.query(Barang).filter(Barang.id_barang==idbarang)

    return render_template('barang/detail_barang.html', barang=barang, title='Detail Barang')

@barang.route('/jual/jual_barang', methods=['GET', 'POST'])
@login_required
def jual_barang():
    """
    Tambah barang ke database
    """
    jual_barang = True

    form = FormBarang()
    if form.validate_on_submit():
        filename = photos.save(form.fotoBarang.data)
        barang = Barang(nama_barang=form.namaBarang.data,
                        harga_barang=form.hargaBarang.data,
                        garansi_barang=form.garansiBarang.data,
                        foto_barang=photos.url(filename),
                        id_user=current_user.id_user,
                        id_jurusan=current_user.id_jurusan)
        try:
            db.session.add(barang)
            db.session.commit()
            flash('Barang sudah berhasil diposting')
        except:
            flash('Error: Barang gagal diposting')
        # return redirect(url_for('user.list_barang'))

    return render_template('barang/form_barang.html', action="Jual", jual_barang=jual_barang, form=form, title="Jual Barang" )

@barang.route('/barang/edit/<idbarang>', methods=['GET', 'POST'])
@login_required
def edit_barang(idbarang):
    """
    Edit Barang
    """

    jual_barang = False

    barang = db.session.query(Barang).filter(Barang.id_barang==idbarang).first()
    form = FormBarang(obj=barang)
    if form.validate_on_submit():
        barang.nama_barang = form.namaBarang.data
        barang.harga_barang = form.hargaBarang.data
        barang.garansi_barang = form.garansiBarang.data
        filename = photos.save(form.fotoBarang.data)
        barang.foto_barang = photos.url(filename)
        db.session.commit()
        flash('Barang berhasil diedit')

        return redirect(url_for('user.profil', username=current_user.username))

    form.namaBarang.data = barang.nama_barang
    form.hargaBarang.data = barang.harga_barang
    form.garansiBarang.data = barang.garansi_barang
    form.fotoBarang.data = barang.foto_barang
    return render_template('barang/form_barang.html', action="Edit", jual_barang=jual_barang, form=form, barang=barang, title="Edit Barang")

@barang.route('/barang/hapus/<idbarang>', methods=['GET', 'POST'])
@login_required
def hapus_barang(idbarang):
    """
    Hapus barang
    """
    barang = Barang.query.get_or_404(idbarang)
    db.session.delete(barang)
    db.session.commit()
    flash("Barang sudah berhasil dihapus")

    return redirect(url_for('user.list_barang'))

    return render_template(title="Hapus Barang")

app/templates/barang/detail_barang.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Profil {{current_user.username}} {% endblock %}
{% block body %}

<div class="tile is-ancestor">
    <div class="tile is-parent is-4">
        <div class="tile is-child box has-background-light is-shadowless">
            {% for detail in barang %}
            <div class="box">
                <figure class="image is-1by1">
                    <img src="{{ detail.foto_barang }}" alt="{{ detail.nama_barang }}">
                </figure>
            </div>
        </div>
    </div>
    <div class="tile is-parent">
        <div class="tile is-child box has-background-white is-shadowless">
            <div class="title">{{ detail.nama_barang }}</div>
            <span class=" title is-4 has-text-danger">{{ "Rp {:,}".format(detail.harga_barang).replace(',','.') }}</span>
            <br><br>
            <table class="table is-fullwidth">
                <tbody>
                    <tr>
                        <td>Penjual</td>
                        <th>{{ detail.barang.username }}</th>
                    </tr>
                    <tr>
                        <td>Kontak</td>
                        <th>{{ detail.barang.no_hp }}</th>
                    </tr>
                    <tr>
                        <td>Fakultas</td>
                        <th>{{ detail.jurusan.fakultas.nama_fakultas }}</th>
                    </tr>
                    <tr>
                        <td>Jurusan</td>
                        <th>{{ detail.jurusan.nama_jurusan }}</th>
                    </tr>
                    <tr>
                        <td>Garansi</td>
                        <th>
                            {% if detail.garansi_barang %}
                                Ada
                            {% else %}
                                Tidak ada
                            {% endif %}
                        </th>
                    </tr>
                </tbody>
            </table>

            <a class="button is-primary is-outlined" href="{{ url_for('barang.edit_barang', idbarang=detail.id_barang) }}">Edit</a>

            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/barang/form_barang.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if jual_barang %}
        Jual Barang
    {% else %}
        Edit Barang
    {% endif %}
{% endblock %}
{% block body %}

<div class="tile is-ancestor">
    <div class="tile is-parent is-4">
        <div class="tile is-child box has-background-light is-shadowless">
            <div class="box">
                {% if jual_barang %}
                <figure class="image is-1by1">
                    <img src="https://bulma.io/images/placeholders/480x480.png">
                </figure>
                {% else %}
                    <figure class="image is-1by1">
                        <img src="{{ barang.foto_barang }}" alt="{{ barang.nama_barang }}">
                    </figure>
                {% endif %}
                <br>
            </div>
        </div>
    </div>
    <div class="tile is-parent">
        <div class="tile is-child box has-background-light is-shadowless">
            {% if jual_barang %}
            <div class="title has-text-danger">Jual Barang</div>
            {% else %}
            <div class="title has-text-danger">Edit Profil</div>
            {% endif %}
            <div class="box">
                <article class="columns">
                    <div class="column is-12-desktop">
                        <div class="content">
                            
                                {{ wtf.quick_form(form) }}

                        </div>
                    </div>
                </article>
            </div>
        </div>
    </div>
</div>
{% endblock %}